### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by JangoBritt** [fuzzysb/SmartThings#1]
I've followed the instructions to the letter, but am still getting "An unexpected error occurred" after entering my advanced options (21,17,TADO_MODE)

I first get a green banner saying "Tado (Connect) is now installed and automating" and then I get the red banner with "An unexpected error occured"

There is no further info in the app.

I should point out that I am setting this up remotely at the moment, so not on the same network as the smartthings hub, or the tado bridge... but that shouldn't make a difference, right?

**Comment by fuzzysb** [comment]
Yup that should not make a difference.  What shard are you on? And do the devices you select appear under your devices.  Best thing to do is get me the logs from the my Tado (connect)  smartapp along with the logs under any devices that appear temporarily.  I am presuming the creation or initial poll of a device is failing. Which devices do you own? Make sure when you post the logs you search and replace your username or password from the logs

**Comment by JangoBritt** [comment]
graph-eu01-euwest1.api.smartthings.com

I can see my Heating zone in the tado (connect) smartapp when I try to configure it, but it won't actually complete the app configuration, so the Tado isn't showing up as a device.

It's a tado heating thermostat (hopefully will be adding some radiator valves when they show up)

I should add that my Tado zone is just called "Heating"

> 148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: error java.lang.NullPointerException: Cannot get property 'device' on null object @ line 925
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Some Devices were not found....creating Child Device Heating
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug getChildDevices(false), children=0
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing parseZoneResponse.successTrue
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug [[HEATING|1|Heating:Heating]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing parseZonesResponse: [[dazzleEnabled:false, id:1, deviceTypes:[RU01], name:Heating, reportAvailable:true, devices:[[serialNo:RU1410FT01051983512576, connectionState:[timestamp:2016-12-02T16:19:20.214Z, value:true], shortSerialNo:RU1983512576, deviceType:RU01, characteristics:[capabilities:[INSIDE_TEMPERATURE_MEASUREMENT, IDENTIFY]]]], type:HEATING, supportsDazzle:true]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing 'sendCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing 'sendCommand.getzones'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Installed with settings: [username:*****, manualmode:TADO_MODE, defCoolingTemp:18, defHeatingTemp:21, password:*****, devices:[HEATING|1|Heating]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug calling weatherStatus Method
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Send thermostatSetpoint Event Fired
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Read humidity: 46.2
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Http Params ([uri:https://my.tado.com, path:/api/v2/homes/55826/weather, requestContentType:application/json, query:[username:*****, password:*****]])
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Read tadoMode: HOME
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Send heatingSetpoint Event Fired
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Send thermostatMode Event Fired
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Send Temperature Event Fired
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Read temperature: 20
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing parseResponse.successTrue
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing parseResponse: [setting:[power:ON, type:HEATING, temperature:[celsius:20, fahrenheit:68]], preparation:null, overlay:null, link:[state:ONLINE], activityDataPoints:[heatingPower:[timestamp:2016-12-02T16:26:11.235Z, percentage:19, type:PERCENTAGE]], overlayType:null, tadoMode:HOME, geolocationOverride:false, sensorDataPoints:[insideTemperature:[timestamp:2016-12-02T16:19:20.220Z, celsius:20.02, precision:[celsius:0.1, fahrenheit:0.1], fahrenheit:68.04, type:TEMPERATURE], humidity:[timestamp:2016-12-02T16:19:20.220Z, percentage:46.2, type:PERCENTAGE]], geolocationOverrideDisableTime:null]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Temperature Unit is C
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing 'sendCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Http Params ([uri:https://my.tado.com, path:/api/v2/homes/55826/zones/1/state, requestContentType:application/json, query:[username:*****, password:*****]])
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:25 PM: debug Executing 'sendCommand.statusCommand'
95bd8284-f5ed-4c1b-ad45-721154f31b19  4:32:25 PM: debug Executing 'refresh'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug [[HEATING|1|Heating:Heating]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug Executing parseZoneResponse.successTrue
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug Executing parseZonesResponse: [[dazzleEnabled:false, id:1, deviceTypes:[RU01], name:Heating, reportAvailable:true, devices:[[serialNo:RU1410FT01051983512576, connectionState:[timestamp:2016-12-02T16:19:20.214Z, value:true], shortSerialNo:RU1983512576, deviceType:RU01, characteristics:[capabilities:[INSIDE_TEMPERATURE_MEASUREMENT, IDENTIFY]]]], type:HEATING, supportsDazzle:true]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug Executing 'sendCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug Http Params ([uri:https://my.tado.com, path:/api/v2/homes/55826/zones, requestContentType:application/json, query:[username:*****, password:*****]])
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug Executing 'sendCommand.getzones'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:16 PM: debug In Advanced Options
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:13 PM: debug [[HEATING|1|Heating:Heating]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:13 PM: debug Executing parseZoneResponse.successTrue
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:13 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:13 PM: debug Executing parseZonesResponse: [[dazzleEnabled:false, id:1, deviceTypes:[RU01], name:Heating, reportAvailable:true, devices:[[serialNo:RU1410FT01051983512576, connectionState:[timestamp:2016-12-02T16:19:20.214Z, value:true], shortSerialNo:RU1983512576, deviceType:RU01, characteristics:[capabilities:[INSIDE_TEMPERATURE_MEASUREMENT, IDENTIFY]]]], type:HEATING, supportsDazzle:true]]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:12 PM: debug Executing 'sendCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:12 PM: debug Http Params ([uri:https://my.tado.com, path:/api/v2/homes/55826/zones, requestContentType:application/json, query:[username:*****, password:*****]])
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:12 PM: debug Executing 'sendCommand.getzones'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:12 PM: debug In listDevices
69b3bdbe-e165-4e22-b4e3-704f043de6f0  4:32:12 PM: debug getChildDevices(false), children=4
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing parseTempResponse.successTrue
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug returning: https://graph-eu01-euwest1.api.smartthings.com:443/api/token/a5326871-d8f5-4a70-8b02-52fde07b4a41/smartapps/installations/148e95af-f4a0-4d4c-8210-20e3f659e273/receivedHomeId
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Http Params ([uri:https://my.tado.com, path:/api/v2/homes/55826, requestContentType:application/json, query:[username:*****, password:*****]])
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing 'sendCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing parseTempResponse: [id:55826, dateTimeZone:Europe/London, geolocation:[longitude:-0.8804775, latitude:52.1876603], temperatureUnit:CELSIUS, address:[zipCode:NN4 5BF, state:null, addressLine2:Grange Park, addressLine1:56 Wake way, country:GBR, city:Northampton], christmasModeEnabled:true, name:Wake way, partner:null, installationCompleted:true, contactDetails:[phone:+447780955431, email:*****, name:Adam Davidson], simpleSmartScheduleEnabled:true]
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Got HomeID Value: 55826
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing 'sendCommand.getidCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Output status: 200
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing parseMeResponse.successTrue
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing 'sendCommand'
148e95af-f4a0-4d4c-8210-20e3f659e273  4:32:09 PM: debug Executing 'sendCommand.getidCommand'
 4:31:02 PM: info Waiting on events...

**Comment by fuzzysb** [comment]
OK so strange.  Looking at your log from the smartapp all queries are working and I can see it made a child device so the issue is the initial poll.  But I can only assist if I get the log from the device called Heating that exists briefly before its deleted.  But you should see Heating listed in the top of live logging window if it is running whilst the smartapp is being installed.  If you can get that to me I can check.... I'm hoping it's not caused by the update to the tado api that makes rather Christmas appear in your tado app

**Comment by fuzzysb** [comment]
OK I have managed to replicate your issue.  Fix will be online soon

**Comment by fuzzysb** [comment]
thanks for bringing this to my attention, this should now work correctly, please update your smartapp and all device types. the issue was caused by me overwriting a version where i had already fixed this with an older version where it was not...schoolboy error :)
