### ISSUE TITLE
Set Temperature Unit

### ISSUE THREAD

**Issue by JangoBritt** [fuzzysb/SmartThings#2]
Hi Fuzzy! Thanks for fixing the bug, it's now showing up in My Devices.

One question though, perhaps I'm doing something wrong.

How do I set the Default Temperature Unit? If I click on the "recently" tab, I see Outside Temperature is 7 deg C, Heating Setpoint 20 deg C, but on the "Right Now" Tab, it is displaying everything in Fahrenheit (45deg and 68deg respectively)

I realise that's just a display issue in the SmartThings app, and when I port it through to HomeBridge, it will probably appear correctly in Celsius, but it would still be nice to fix.

**Comment by fuzzysb** [comment]
OK I'm looking at my heating device and it's all displaying in Celsius and not Fahrenheit.  The bizarre thing is that all display boxes use the same data to choose to display C or F dependant on your location temp option. First check that. Then can you post a screen grab

**Comment by JangoBritt** [comment]
Yes, that's sorted... I hadn't found the Temperature Unit option in the location settings. I'll close this, and accept my shame.
