### ISSUE TITLE
Tado Away Mode as Presence

### ISSUE THREAD

**Issue by JangoBritt** [fuzzysb/SmartThings#3]
Is it at all possible to use Tado (who already knows the presence of the home users) as a presence indicator? So that when Tado goes into Away mode, "everyone" is set to away, and vice versa when it returns to Home mode?

**Comment by fuzzysb** [comment]
I already have a device type for bringing Tado presence to smarthings. 

https://github.com/fuzzysb/SmartThings/tree/master/DeviceTypes/fuzzysb/Tado-Heating-User-Presence

However I envisage a different presence method for this smartapp as there are more reliable presence indicators within smartthings

**Comment by JangoBritt** [comment]
Yea, I know that I could install ST on my Wife's phone too, but I'm painfully aware that everything I do has to have credible WAF (Wife Acceptance Factor), so would have liked to avoid installing another app on her phone.

Also, it would mean that rather than building complex rules like  if My phone is away and My wife's phone is away, set "goodbye" if my phone is back, and my wife's phone is away, set "welcome home" if my wife's phone is back, and my phone is away set "welcome home"

When the Occupancy is already detected by the tado, I could do all that with a single sensor type.

**Comment by fuzzysb** [comment]
OK,  I'm just not a fan of using a mobile phone for presence as I think it's unreliable.  But if you use the device type I linked to it can do what your after using something like CoRE just to set the rule that if all leave set away etc.. 

I personally use a combination of ST hardware presence fobs and WiFi detection using my Router which works incredibly well. So what I wanted to do was take ST Presence and create a object in Tado that updates and changes the tado status as per the ST status.  

I might eventually do both methods in the smartapp but it would never be anything more than just updating presence in ST, as your scenario I imagine would not be a usual use case so I would leave it open so got would always need the likes of core etc...  To actually set the home/away modes
