### ISSUE TITLE
Can't port through JSON to HomeBridge

### ISSUE THREAD

**Issue by JangoBritt** [fuzzysb/SmartThings#4]
so I know this may not be a problem here, but I thought I should mention it.

I'm trying to port the TADO through SmartThings into HomeBridge so that I can get it on HomeKit on my iPhone. I know it's a round-about way of doing it, but hey-ho.

Anyway, when I pull the TADO thermostats through the JSON API into homebridge I get three devices per thermostat, one with Humidity, that works, and two with temperature (one with heating, and one with both heating and humidity) that show as Not Responding, and do not show the temperature. :-(

I have an issue raised on the homebridge-smartthings thread too. https://github.com/pdlove/homebridge-smartthings/issues/122

**Comment by JangoBritt** [comment]
Actually, now that I've changed the Temperature units to Celsius, it's updating in HomeKit.

However, I'm still surprised to get three separate devices.

One with just Detected Temperature (I guess Device Type Temperature Sensor)
One with Just Humidity(I guess Device Type Humidity Sensor)
One with Detected Temperature, Target Temperature, & Humidity (I guess Device Type Thermostat)

**Comment by fuzzysb** [comment]
This really is not something I will be able to assist with at all. My device type conforms to the SmartThings Api for Thermostats, why it would not work correctly is beyond my expertise as I have absolutely no experience with Homekit as I personally loathe apple hardware these days. I will leave this issue open for the time being. If you get traction for a possible cause or a solution in the homekit thread please update this issue accordingly. Sorry I can't help further at the moment.

**Comment by fuzzysb** [comment]
I had another thought. If you edit your Tado heating thermostat device handler and comment out the lines

capability "Temperature Measurement"
capability "Relative Humidity Measurement"
		
I'm wondering if your homekit will display only a single device?

**Comment by JangoBritt** [comment]
Yes, it does indeed remove the additional tiles in HomeKit.

I suspect that what happens is that it's recognised as a single device, but the Home app displays it in a separate tile because it's too much information for one tile which is strange, because all the information exists there in the details pane of the main tile. odd.

**Comment by fuzzysb** [comment]
OK good to know.  However I still think that those capabilities should remain in place as they also are on all other Thermostats in place in ST
